version: '3.8'

services:
  django:
    build: .
    container_name: django_app
    command: sh -c "python /app/manage.py migrate --settings=config.settings && python /app/manage.py runserver 0.0.0.0:8000 --settings=config.settings"
    # command: sh -c "sleep 10000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - rabbitmq
    # env_file:
    #   - .env

  celery-worker:
    build: .
    container_name: celery_worker
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - redis
    # env_file:
    #   - .env

  celery-beat:
    build: .
    container_name: celery_beat
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - redis
      - django
    # env_file:
    #   - .env

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq-ratewise
    # environment:
    #   RABBITMQ_DEFAULT_USER: guest
    #   RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ratewise
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
