apiVersion: apps/v1
kind: Deployment
metadata:
  name:  celery-worker
  namespace: ratewise
  labels:
    app: celery-worker
spec:
  selector:
    matchLabels:
      app: celery-worker
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name:  celery-worker
        image:  ratewise:1.1.1
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 100m
            memory: 500Mi
        command: ["celery", "-A", "config", "worker", "--loglevel=info"]
