apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: ratewise
  labels:
    app: postgresql
spec:
  serviceName: "postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "ratewise"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  
      volumes:
          - name: postgres-storage
            persistentVolumeClaim:
              claimName: postgres-pvc
    
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: ratewise
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
