# Generated by Django 5.1.5 on 2025-01-27 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("RateWise", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="average_score",
        ),
        migrations.RemoveField(
            model_name="document",
            name="number_of_ratings",
        ),
        migrations.RemoveField(
            model_name="document",
            name="standard_deviation",
        ),
    ]
